<?php

namespace Tests\Feature\app\Repositories;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

/**
 * Class UserRepository
 * @package Tests\Feature\app\Repositories
 */
class UserRepository extends TestCase
{

    public $userRepository;

    /**
     *
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userRepository = $this->app->make(\App\Repositories\UserRepository::class);

    }

    /**
     * A basic test example.
     *
     * @dataProvider  provider
     * @return void
     */
    public function testExample($a, $b, $c)
    {

       $result = $this->userRepository->create();
        $this->assertTrue($result);
    }


    /**
     * @return array
     */
    public function provider()
    {
        return array(
            array(0, 0, 0),
            array(0, 1, 1),
            array(1, 0, 1),
            array(1, 1, 3)
        );
    }
}
